### ISSUE TITLE
Publish as NPM

### ISSUE THREAD

**Issue by KasperAndersson** [23/GlueFrame#2]
Would be nice to see this published as a NPM.

How to - https://gist.github.com/coolaj86/1318304

Thanks in advance

**Comment by KasperAndersson** [comment]
@kkabell @steffentchr

**Comment by kkabell** [comment]
@KasperAndersson Thanks for the suggestion! Should be ready at https://www.npmjs.com/package/glueframe

**Comment by KasperAndersson** [comment]
Nice!
