### ISSUE TITLE
Switch current video

### ISSUE THREAD

**Issue by Mamboleoo** [23/GlueFrame#4]
Hello,

I'm currently working with GlueFrame for a project and I would like to change the current video with a new one based on a new ID & Token.
In the Player.js file from 23 Video I see the function to update those values, but with GlueFrame it doesn't seem to work.

Thanks for helping me,
Louis

**Comment by steffentchr** [comment]
Hi @Mamboleoo -- you can do this using `Player.set('photo_id', 12345)` if the video is already loaded in the recommendation list. If not, the player needs to be bootstrapped again with new data and token, which isn't currently exposed as getters/setters in the Player. 

[for background, this is a TwentyThree-specific question]

**Comment by Mamboleoo** [comment]
Thanks for your answer !
I'm gonna check with TwentyThree about this :)
