### ISSUE TITLE
Documentation: Events and Properties

### ISSUE THREAD

**Issue by MCsereVertic** [23/GlueFrame#5]
Is there any chance to provide us with a list of available properties that we can take get from a video?
Also a list of all potential events where we could bind a function?

Thanks

**Comment by cpnielsen** [comment]
Hi @MCsereVertic 

This is probably better directed at https://github.com/23/player, as GlueFrame is simply a connection framework and the player holds and provides all the properties (which may change).

For now, a quick list of available properties (`Player.get(<property>)`) as of yesterday:

- accentColor
- actionsShown
- advancedContextMenu
- api
- autoPlay
- bigPlaySource
- bootstrapped
- browseMode
- browseThumbnailHeight
- browseThumbnailWidth
- bufferTime
- clips
- currentTime
- currentVideoEngagement
- debugParameters
- diggLink
- displayDevice
- displayPlayProgress
- displaying360
- domain
- downloadUrl
- duration
- eingebautConstructor
- embedCode
- enableSubtitles
- ended
- error
- facebookLink
- fullscreen
- googleLink
- hasLink
- hasQualitySwitching
- hasRecommendations
- hasSlides
- hasSubtitles
- horizontalPadding
- identityAllowClose
- identityCountdown
- identityCountdownText
- infoShown
- isLive
- isStream
- isTouchDevice
- is_dev
- linkBoxValue
- linkedinLink
- liveBufferRegion
- liveDuration
- loading
- locales
- localesArray
- logoSource
- mailLink
- mainUrl
- maxLengthDVR
- menuLeft
- menuTop
- mutedAutoPlay
- nextVideo
- paused
- permission_level
- playerSize
- player_id
- playflowPosition
- playing
- playlistClickMode
- podcastLink
- protectionMethod
- protectionStatus
- protocol
- qualities
- qualitiesArray
- quality
- recommendationMethod
- recommendations
- rssLink
- scrubberTime
- sections
- seekedTime
- seeking
- settings
- shortcutsDisabled
- showBrowse
- showDomain
- showDownload
- showLinkBox
- showLivePreview
- showLogo
- showMenu
- showSeeking
- showSharing
- showSlides
- showStreamNotLive
- siteLink
- slideMode
- slideModes
- slides
- socialSharing
- source
- src
- stalled
- stream_has_dvr
- streams
- subtitleLocale
- subtitleMenuWidget
- subtitleText
- subtitles
- supportsFullscreen
- supportsVolumeChange
- totalEngagement
- tumblrLink
- twitterLink
- url
- uuid
- verticalPadding
- video
- videoActionPlaying
- videoActions
- videoElement
- videoLink
- videoProtected
- video_album_id
- video_aspect_ratio
- video_base_url
- video_content
- video_duration
- video_frames_height
- video_frames_src
- video_frames_width
- video_has_frames
- video_is_360
- video_live_id
- video_num_frames
- video_one
- video_photo_id
- video_playable
- video_sharable
- video_title
- video_token
- video_tree_id
- video_type
- volume
- volumeMuted
